version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - danmurf
- name: Dependabot Auto Merge
  uses: ahmadnassri/action-dependabot-auto-merge@v2.2.0
